site_name: Working Group Data Literacy 
site_url: https://konrad.github.io/single-source-publishing-test/
nav:
  - Partner-Hochschulen: partner_hochschulen.md
  - Data Literacy: data_literacy.md
  - Themen: categories
  - Ãœber diese Seite: ueber_diese_seite.md


theme:
    name: mkdocs
    locale: de

plugins:
    - categories:
        no_nav: true
